### ISSUE TITLE
Using in a github action, but failed with no output

### ISSUE THREAD

**Issue by techyCoder81** [lukaszraczylo/semver-generator#14]
**Describe the bug**
Tried to use this as part of a github action, but it failed without any output. It is unclear how to get debug output in this format. If it could work as described, this would absolutely fill a need for our project that I otherwise cannot find a plugin working for. If this is an issue with my configuration, please do let me know. I am also unsure if the "build semver-generator@v1" step at the beginning was truly successful or not, as it does have error output despite passing. Any help would be appreciated.
![image](https://user-images.githubusercontent.com/42820193/154761950-12b848dd-f727-4953-83c3-7579b8dd2dd3.png)

**Output with debug**
(could not get debug output, as this is undocumented for github actions)

**Expected behavior**
Expected action to succeed or show configuration issues.

**Additional context**
The failed run: https://github.com/HDR-Development/HewDraw-Remix/runs/5252877868?check_suite_focus=true
config file at this time: https://github.com/HDR-Development/HewDraw-Remix/blob/8da98b893e92979baebcc26d8e68257cbcfe3a47/.github/workflows/semver_config.yaml
the action step: https://github.com/HDR-Development/HewDraw-Remix/blob/8da98b893e92979baebcc26d8e68257cbcfe3a47/.github/workflows/build.yml#L104

**Comment by lukaszraczylo** [comment]
@techyCoder81 Could you make sure that you have `semver.yaml` file with configuration in the root of the repository? :)
