### ISSUE TITLE
Unable to find config file semver.yaml

### ISSUE THREAD

**Issue by Ashtonian** [lukaszraczylo/semver-generator#15]
**Describe the bug**
If installed using go it doesn't seem to work out of the box. 

**Output with debug**
semver-generator generate -l
Unable to find config file semver.yaml

**Comment by lukaszraczylo** [comment]
Hello @Ashtonian, have you created semver.yaml file in the root directory of your repository? It needs a config to run, even if it's an empty file although I may remove this requirement if it causes trouble or add appropriate switch like `-noconfig` to make sure that nobody experiences any weird behaviour :)

**Comment by Ashtonian** [comment]
ahh yea, copied the default one in the root directory and it worked. My preference would be to have a default that requires  near 0 user input :).

**Comment by lukaszraczylo** [comment]
I'll add it this weekend :)
