### ISSUE TITLE
More specific name for the default config

### ISSUE THREAD

**Issue by hipertracker** [lukaszraczylo/semver-generator#2]
The default config.yaml is too generic and can be confused with other yaml files in the project. Maybe it would be better to have it more unique default name, like semver.yml, sem.yml or sem-version.yml

**Comment by lukaszraczylo** [comment]
You can specify config file with the `-c` flag, for example `semver-gen -c semver.yml` so I am not sure if it's required.
I'll keep it in the backlog just in case there's more votes in future.

**Comment by lukaszraczylo** [comment]
Resolved in 6cbe480
