### ISSUE TITLE
Check if there is a newer version

### ISSUE THREAD

**Issue by hipertracker** [lukaszraczylo/semver-generator#4]
The application should have an option to check if there is a newer version to the download.

**Comment by lukaszraczylo** [comment]
<img width="949" alt="Screenshot 2021-05-12 at 10 56 22" src="https://user-images.githubusercontent.com/2182556/117956185-b86e0a00-b310-11eb-98b0-4d950a51ee22.png">

Added in v1.1.7 as a part of `-v` switch.
This and another option requires setting up the github credentials, which is reflected in documentation.
