### ISSUE TITLE
Force parameter not working

### ISSUE THREAD

**Issue by hipertracker** [lukaszraczylo/semver-generator#6]
❯ semver-gen -v
semver-gen 1.0.32

For
```
force:
  major: 0
  minor: 0
  patch: 0

❯ semver-gen generate -c config.yml -r https://github.com/hipertracker/words_extractor
SEMVER 1.4.12
```
which is correct, but for

```
force:
  major: 1
  minor: 1
  patch: 1

❯ semver-gen generate -c config.yml -r https://github.com/hipertracker/words_extractor
SEMVER 1.4.12
```
this is confusing. Should not force enforce the given 1.1.1 version incremented by all commits?

**Comment by lukaszraczylo** [comment]
No, force parameter sets the starting parameters for the release.

Let's say you've published release `1.2.3` before using `semver-gen`
You can then set `1.2.3` as the starting parameter, add the commit message hash from which it'll start counting using the `semver-gen`.

Forcing `1.1.1` as a permanent version defies the need for the `semver-gen` :)
